apiVersion: v1
kind: Service
metadata:
  name: litecoin
  namespace: default
  labels:
    app: litecoin
spec:
  ports:
  - name: port1
    port: 9332
    protocol: TCP
  - name: port2
    port: 9333
    protocol: TCP
  - name: port3
    port: 19332
    protocol: TCP
  - name: port4
    port: 19333
    protocol: TCP
  - name: port5
    port: 19444
    protocol: TCP
  selector:
    app: litecoin
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litecoin
spec:
  selector:
    matchLabels:
      app: litecoin
  serviceName: "litecoin"
  replicas: 1
  template:
    metadata:
      labels:
        app: litecoin
    spec:
      containers:
      - name: litecoin
        image: litecoin
        # using local docker registry
        imagePullPolicy: Never
        command: ["litecoind"]
        ports:
        - containerPort: 9332
          name: port1
        - containerPort: 9333
          name: port2
        - containerPort: 19332
          name: port3
        - containerPort: 19333
          name: port4
        - containerPort: 19444
          name: port5
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"          
        volumeMounts:
        - name: vol1
          mountPath: /etc/data/          
  volumeClaimTemplates:
  - metadata:
      name: vol1
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi

